application: ballet
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.+)
  static_files: html/\1
  upload: html/(.*)

- url: /
  static_files: html/Ad.html
  upload: html/Ad.html

libraries:
- name: webapp2
  version: "2.5.2"
